#!/bin/sh

get_by_num () {
  URL=$(curl -sL xkcd.com/$1 |								\
	grep src |									\
	grep -io 'imgs.xkcd.com\/comics\/[[:alnum:]_()]\+.\(jpg\|\|png\|\|gif\)' |	\
	tail -n1) 									
  IMGEXT=$(echo $URL | grep -o '.\w\+$')
  curl -so $1$IMGEXT $URL &&								\
  open $1$IMGEXT && 									\
  rm $1$IMGEXT
}


if [ -z $1 ]
then
MAXNUM=$(curl -sL xkcd.com |				\
	 grep -i 'permanent link to this comic:' |	\
	 grep -o '/[[:digit:]]\+/' | 			\
	 sed s/'\/'//g)
IMGNUM=$((1 + ($(date '+%s')*$$) % $MAXNUM))
echo $IMGNUM
get_by_num $IMGNUM
else
get_by_num $1
fi
