#!/bin/sh

get_by_num () {
  echo $1
  curl -sL xkcd.com/$1 |						\
  grep src |								\
  grep -o 'imgs.xkcd.com\/comics\/[[:alnum:]_()]\+.\(jpg\|\|png\)' |	\
  tail -n1 |								\
  xargs curl -so tmp.img && 						\
  open tmp.img && 							\
  rm tmp.img
}

if [ -z $1 ]
then
MAXNUM=$(curl -sL xkcd.com |				\
	 grep -i 'permanent link to this comic:' |	\
	 grep -o '/[[:digit:]]\+/' | 			\
	 sed s/'\/'//g)
IMGNUM=$((1 + ($(date '+%s')*$$) % $MAXNUM))
get_by_num $IMGNUM
else
get_by_num $1
fi



